{
  "props": {
    "author": "Ryzhenkov Yevgeny",
    "version": "1.0.0.0"
  },
  "components": {
    "cfg": {
      "type": "script\\storage\\IniStorage",
      "x": 96,
      "y": 32,
      "props": {
        "path": "config.ini",
        "autoSave": true,
        "multiLineValues": "1"
      }
    },
    "groups": {
      "type": "script\\storage\\IniStorage",
      "x": 160,
      "y": 32,
      "props": {
        "path": "groups.ini",
        "autoSave": true,
        "multiLineValues": "1"
      }
    },
    "persons": {
      "type": "script\\storage\\IniStorage",
      "x": 32,
      "y": 32,
      "props": {
        "path": "persons.ini",
        "autoSave": true,
        "multiLineValues": "1"
      }
    }
  }
}